Class iris.src.demo.rm.SalesCSV Extends %RegisteredObject
{

XData RecordMap
{
<Export generator="RecordMap" version="1">
  <RecordMap name="SalesCSV" type="CSV" delimiter="," header="true" quote="&quot;">
    <Record name="Row">
      <Field name="order_id" />
      <Field name="customer_id" />
      <Field name="amount" />
      <Field name="currency" />
      <Field name="order_date" />
    </Record>
  </RecordMap>
</Export>
}

}
